### ISSUE TITLE
gist同步用不了

### ISSUE THREAD

**Issue by jhhd88** [suziwen/ZeroOmega#17]
![image](https://github.com/user-attachments/assets/bbb3ff45-f68c-4f00-b801-12033f858817)

更新到3.3.0版本后，按要求填写gist信息，但点击同步就会出现以上错误提示。

**Comment by suziwen** [comment]
[3.3.1](https://github.com/suziwen/ZeroOmega/releases/tag/3.3.1) 可以自动识别这两种格式了

**Comment by afantee** [comment]
还是不能同步，不知何故！

**Comment by suziwen** [comment]
@afantee  看一下你的 gist 是否能正常访问，你有没有开通 gist 权限．

请重开一个新 issue， (这个 issue 跟你的问题无关的) 并贴上尽可能多的详细信息，比如有什么错误提示，日志里有什么信息，操作系统，浏览器版本等．
