### ISSUE TITLE
Edge 商店版更新

### ISSUE THREAD

**Issue by leic4u** [suziwen/ZeroOmega#20]
Chrome 商店和 Firefox 商店都已经更新 `3.3.3` 和 `3.3.4` 两个版本了，Edge 商店还在 `3.3.2`，请大佬安排一下 Edge 商店的更新，辛苦了，感谢！

**Comment by suziwen** [comment]
上星期提交的，原本应该这几天就审核通过，但今天又发现了个 bug , 发布了 3.3.4, 重新提交审核， Edge 商店审核时间又要被重置，重新等大概 7 天．

**Comment by leic4u** [comment]
好的，没忘掉就好。感谢。❤️
