### ISSUE TITLE
ZeroOmega is occasionally disabled on some tabs in Firefox

### ISSUE THREAD

**Issue by amirrh6** [suziwen/ZeroOmega#22]
### ZeroOmega version / ZeroOmega 版本
3.3.6

### Browser version & OS version / 浏览器名称、版本及操作系统版本
Firefox 129.0.1 / Ubuntu 24.04

### Problem description / 问题描述
ZeroOmega occasionally needs to manually enabled on some tabs by clicking once or twice on its toolbar icon in order to function correctly.

It **isn't really easy** to reproduce this bug but I will try my best to explain. 
I started noticing this issue since v3.3.6 but I can not say for sure that this issue was not present before.

I am using an auto-switching profile which uses a proxy except for certain sites. I noticed that a website is showing an error because my real IP is blacklisted because of my region. I tried refreshing the page several times but I faced the same error. Once I clicked on ZeroOmega's toolbar icon twice and refreshed again, the issue was solved and the proxy seemed to be applied.

[Screencast from 2024-08-13 19-16-07.webm](https://github.com/user-attachments/assets/5cca07b2-2b21-439d-bc10-ca5ce12813a0)

**Comment by suziwen** [comment]
Can't be reproduced, just wait and see if other people report the same problem.

**Comment by suziwen** [comment]
Maybe `3.3.7` use async startup cause problem, I have optimized on `3.3.8`.

**Comment by amirrh6** [comment]
I can not longer reproduce the issue on latest version of the extension. I will re-open the issue if I happened to face the issue again.
Thank you
