### ISSUE TITLE
点击“资源未加载”无法弹出选项

### ISSUE THREAD

**Issue by xujingkai** [suziwen/ZeroOmega#4]
感谢大佬适配V3，这边有个问题不知是否可以解决

系统环境：
Macos 14.4.1 (23E224)

浏览器环境：
[Arc浏览器](https://arc.net/)
版本1.41.0 (49440)
Chromium Engine Version 124.0.6367.92

问题现象：
点击“资源未加载”无法弹出选项。
截图如下：
https://github.com/suziwen/ZeroOmega/assets/14089362/a1cc0d98-d61d-4aac-a566-8d42f02cc5cc

其他信息：
SwitchyOmega也有这个问题，不清楚是否应该反馈在这里

**Comment by xujingkai** [comment]
点击“添加条件”也打不开，看商品评论也有人提到

**Comment by suziwen** [comment]
测试了下， Arc 浏览器下确实有问题。

好像是 Arc 浏览器不允许 popup 窗口里的链接跳转到其他页面引起的，也就是无法执行 `document.location.href = "新地址"`.

**Comment by xiaotianhu** [comment]
按住 CMD 再点，可以在新窗口打开，可以勉强用了。

**Comment by suziwen** [comment]
https://github.com/suziwen/ZeroOmega/releases/tag/3.2.2
