### ISSUE TITLE
Arc浏览器中，点击 未加载资源， 无法正常打开弹窗修改策略

### ISSUE THREAD

**Issue by xujipm** [suziwen/ZeroOmega#6]
### Browser version & OS version / 浏览器名称、版本及操作系统版本
Arc
版本1.41.0 (49440)
Chromium Engine Version 124.0.6367.92

### Problem description / 问题描述

(Please provide as much detail as possible. We recommend the following format.)
(请尽可能多提供一些细节。我们推荐使用下面的格式。)
![image](https://github.com/suziwen/ZeroOmega/assets/3202911/c31576d6-d6a9-4609-8038-41a79545a69c)

点击 未加载资源， 无法正常打开弹窗修改策略
#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

1.
2.
3.

**Comment by suziwen** [comment]
duplicate #4
